# Generated by Django 4.0.2 on 2024-11-04 11:09

from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_identifier',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='avatar_identifier'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('legal', 'Legal'), ('teacher', 'Teacher')], default='regular', max_length=10, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Active Code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=200, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family',
            field=models.CharField(blank=True, max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('True', 'Male'), ('False', 'Female ')], default='True', max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Register Date'),
        ),
    ]
